FROM alpine:latest


RUN apk add --no-cache \
    g++ \
    cmake \
    make \
    linux-headers \
    iproute2 \
    net-tools \
    tcpdump


COPY . /app
WORKDIR /app


RUN mkdir -p build-test && \
    cd build-test && \
    cmake .. -DCMAKE_BUILD_TYPE=Debug -DProject_ENABLE_UNIT_TESTING=ON -DProject_USE_GTEST=ON && \
    cmake --build .


CMD ["/bin/sh"]

