#!/usr/bin/env python3
"""Embed a Metal kernel source file as a C byte array header.

The WireLab Metal parser compiles its kernel at runtime with
`newLibraryWithSource:` (no precompiled .metallib shipping machinery needed),
so the .metal source is embedded into the binary as a byte array.

Usage: embed_metal.py <input.metal> <output.h>
"""

import sys


def main() -> int:
    if len(sys.argv) != 3:
        print(f"usage: {sys.argv[0]} <input.metal> <output.h>", file=sys.stderr)
        return 2
    source_path, output_path = sys.argv[1], sys.argv[2]
    with open(source_path, "rb") as source_file:
        data = source_file.read()

    lines = [
        "// Generated by scripts/embed_metal.py -- do not edit.",
        "namespace wirelab {",
        "namespace metal {",
        "static const unsigned char kernel_source[] = {",
    ]
    for offset in range(0, len(data), 12):
        chunk = data[offset : offset + 12]
        lines.append("  " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    lines.append("};")
    lines.append(f"static const unsigned int kernel_source_len = {len(data)}u;")
    lines.append("}  // namespace metal")
    lines.append("}  // namespace wirelab")

    with open(output_path, "w", encoding="ascii") as output_file:
        output_file.write("\n".join(lines) + "\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
