set(sources
    src/sys_utils.cpp
    src/tap_device.cpp
    src/ethernet_frame.cpp
    src/udp_socket.cpp
    src/vport.cpp
    src/mac_table.cpp
    src/vswitch.cpp
    src/traffic_generator.cpp
    src/packet_analyzer.cpp
    src/packet_batch.cpp
    src/anomaly_detector.cpp
    src/policy_engine.cpp
    src/switch_metrics.cpp
    src/control_protocol.cpp
    src/control_service.cpp
    src/topology.cpp
    src/topology_yaml.cpp
    src/fault_engine.cpp
    src/topology_controller.cpp
)


set(headers
    include/project/expected.hpp
    include/project/joining_thread.hpp
    include/project/sys_utils.hpp
    include/project/tap_device.hpp
    include/project/ethernet_frame.hpp
    include/project/udp_socket.hpp
    include/project/vport.hpp
    include/project/mac_table.hpp
    include/project/vswitch.hpp
    include/project/traffic_generator.hpp
    include/project/packet_analyzer.hpp
    include/project/packet_batch.hpp
    include/project/anomaly_detector.hpp
    include/project/policy_engine.hpp
    include/project/switch_metrics.hpp
    include/project/control_protocol.hpp
    include/project/control_service.hpp
    include/project/topology.hpp
    include/project/fault_engine.hpp
    include/project/topology_controller.hpp
)

set(test_sources
  src/expected_test.cpp
  src/joining_thread_test.cpp
  src/sys_utils_test.cpp
  src/tap_device_test.cpp
  src/ethernet_frame_test.cpp
  src/udp_socket_test.cpp
  src/mac_table_test.cpp
  src/integration_test.cpp
  src/traffic_generator_test.cpp
  src/packet_analyzer_test.cpp
  src/packet_batch_test.cpp
  src/anomaly_detector_test.cpp
  src/policy_engine_test.cpp
  src/switch_metrics_test.cpp
  src/control_protocol_test.cpp
  src/control_service_test.cpp
  src/topology_test.cpp
  src/topology_yaml_test.cpp
  src/fault_engine_test.cpp
  src/topology_controller_test.cpp
)
