set(sources
    src/sys_utils.cpp
    src/tap_device.cpp
    src/ethernet_frame.cpp
    src/udp_socket.cpp
    src/vport.cpp
    src/mac_table.cpp
    src/vswitch.cpp
    src/traffic_generator.cpp
    src/packet_analyzer.cpp
    src/packet_batch.cpp
    src/pcap.cpp
    src/anomaly_detector.cpp
    src/policy_engine.cpp
    src/policy_enforcer.cpp
    src/analysis_pipeline.cpp
    src/switch_supervisor.cpp
    src/switch_metrics.cpp
    src/control_protocol.cpp
    src/control_service.cpp
    src/topology.cpp
    src/topology_yaml.cpp
    src/fault_engine.cpp
    src/topology_controller.cpp
)


set(headers
    include/wirelab/expected.hpp
    include/wirelab/joining_thread.hpp
    include/wirelab/sys_utils.hpp
    include/wirelab/tap_device.hpp
    include/wirelab/ethernet_frame.hpp
    include/wirelab/udp_socket.hpp
    include/wirelab/vport.hpp
    include/wirelab/mac_table.hpp
    include/wirelab/vswitch.hpp
    include/wirelab/traffic_generator.hpp
    include/wirelab/packet_analyzer.hpp
    include/wirelab/packet_batch.hpp
    include/wirelab/pcap.hpp
    include/wirelab/anomaly_detector.hpp
    include/wirelab/policy_engine.hpp
    include/wirelab/policy_enforcer.hpp
    include/wirelab/analysis_pipeline.hpp
    include/wirelab/switch_supervisor.hpp
    include/wirelab/switch_metrics.hpp
    include/wirelab/control_protocol.hpp
    include/wirelab/control_service.hpp
    include/wirelab/topology.hpp
    include/wirelab/fault_engine.hpp
    include/wirelab/topology_controller.hpp
)

set(test_sources
  src/expected_test.cpp
  src/joining_thread_test.cpp
  src/sys_utils_test.cpp
  src/tap_device_test.cpp
  src/ethernet_frame_test.cpp
  src/udp_socket_test.cpp
  src/mac_table_test.cpp
  src/integration_test.cpp
  src/traffic_generator_test.cpp
  src/packet_analyzer_test.cpp
  src/packet_batch_test.cpp
  src/pcap_test.cpp
  src/anomaly_detector_test.cpp
  src/policy_engine_test.cpp
  src/policy_enforcer_test.cpp
  src/analysis_pipeline_test.cpp
  src/switch_supervisor_test.cpp
  src/switch_metrics_test.cpp
  src/control_protocol_test.cpp
  src/control_service_test.cpp
  src/topology_test.cpp
  src/topology_yaml_test.cpp
  src/fault_engine_test.cpp
  src/topology_controller_test.cpp
)
